# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1ff91727cad184334182ed1ac9d7c4ef1c4163640db324b2a797268c9af5ef8d392eb98a60947ae1bae8d8d6d3e69931326a6b3f80dbd24863c1d6c3f78b069

test:
  secret_key_base: 576888b20094f044b8c6270db17503c72dc9436739914ff6caeee7538f387784c05f675bb70e6b1c061ee2cb02863da0eb12a2e7d0592ee8f54e32f0b6afb001

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
